### ISSUE TITLE
Make JoinMidRound configurable

### ISSUE THREAD

**Issue by LaFesta1749** [frankos6/SCPPlugins#43]
Would it be possible to add in the config of JoinMidRound to have for example:
Timer for late joiners: time?
As server owners might want to make it longer than 5 seconds for people that connect slowly. For example 15 seconds or so?

**Comment by frankos6** [comment]
What do you mean by timer? The respawn timer is already configurable with `respawn_timer`, unless you mean the maximum round time, it should be 2 minutes from round start

**Comment by LaFesta1749** [comment]
Currently, there's a number of seconds when a player joins to be spawned as Class-D after the round has started. I'm not sure what the specific number is.

So my request is to add this time in the config of the server so that it can be changed by the server owners.
